trigger:
  branches:
    include:
      - main

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'

variables:
  - name: jdkVersion
    value: '17'
  - group: grupoVariablesDocker
  - name: imageName
    value: '<Nombre de la imagen de Docker>'
  - name: dockerfilePath
    value: '.'
  - name: tag
    value: '$(Build.BuildNumber)'
  - name: nombreRegistroContenedor
    value: ''
  - group: grupoVariablesSonarcloud
  - name: nombreConexionSonarcloud
    value: ''
  - name: rutaDirectorioRaizProyecto
    value: ''
  - name: claveProyectoSonarcloud
    value: ''
  - name: nombreOrganizacionSonarcloud
    value: ''


stages:
  - stage: Stage CI/CD
    displayName: 'CI/CD to development environment'

    jobs:
      - job: DevelopCI
        displayName: 'Develop CI`${tag}'
#        steps:
#          - checkout: self
#          - checkout: templates
#          - template: pipeline/ci.yml@templates
#
#      - job: DevelopCD
#        displayName: 'Develop CD'
#        dependsOn: DevelopCI
#        steps:
#          - checkout: self
#          - checkout: templates
#          - template: pipeline/cd.yml@templates
#
